name: fintech_app
description: Modern fintech mobil uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  local_auth: ^2.1.7
  crypto: ^3.0.3
  intl: ^0.19.0
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
